spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-qbnp-dev
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-qbnp-test
#  请保存为utf8格式